config/routes.rb
Rails.application.routes.draw do
  
root 'signs#index'
resources :signs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController

  def index

  end

  def show

 #  assigning sign variable to the method of grabbing the API info from the Astrology API app

    @sign = get_api_data
  end

  private # conventionally good practice to have special controller method just for the specific controller 

  def get_api_data 

    # {params[:id]} is the custom-made url in the Astrology API that is the sign's name in lowercase
    # the show method simply grabs that id and parses it into the url to grab the sign's individual info
    
     url = "http://www.astrology-api.com/api/signs/#{params[:id]}"
     @response = HTTParty.get(url)

    
  end

  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/[layout_name].html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "BAI - Basic Astrology APP" %></title>
   <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    "application" %>
    <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>


</body>
</html>

app/views/signs/index.html.erb
<body class="body">

<h1 class="text-center welcome"><u>Welcome to Basic Astrology Info: </u></h1><h3 class="text-center welcome">The App that allows you to easily see all of a Zodiac Sign's basic information</h3>


<table id="index-table">

  <thead id="thead-row">
    <th></th>
    <th><h2 class="text-center"><u>Cardinal</u></h2></th>
    <th><h2 class="text-center"><u>Fixed</u></h2></th>
    <th><h2 class="text-center"><u>Mutable</u></h2></th>
  </thead>

  <tr>
    <td><h2 class="text-center">Fire</h2></td>
    <td>
    <%= link_to sign_path("aries")  do %>
    <%= image_tag("Aries.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Aries <%= image_tag("aries-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
    <td>
    <%= link_to sign_path("leo")  do %>
    <%= image_tag("Leo.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Leo <%= image_tag("leo-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
    <td>
    <%= link_to sign_path("sagittarius")  do %>
    <%= image_tag("Sagittarius.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Saggitarius <%= image_tag("sagg-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
  </tr>

  <tr id="earth-row">
    <td><h2 class="text-center">Earth</h2></td>
    <td>
    <%= link_to sign_path("capricorn")  do %>
      <%= image_tag("Capricorn.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Capricorn <%= image_tag("capricorn-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
    <td>
    <%= link_to sign_path("taurus")  do %>
    <%= image_tag("Taurus.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Taurus <%= image_tag("taurus-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
    <td>
    <%= link_to sign_path("virgo")  do %>
    <%= image_tag("Virgo.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Virgo <%= image_tag("virgo-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
  </tr>

  <tr>
    <td><h2 class="text-center">Air</h2></td>
    <td>
    <%= link_to sign_path("libra")  do %>
    <%= image_tag("Libra.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Libra <%= image_tag("libra-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
    <td> 
    <%= link_to sign_path("aquarius")  do %>
    <%= image_tag("Aquarius.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Aquarius <%= image_tag("aquarius-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
    <td>
    <%= link_to sign_path("gemini")  do %>
    <%= image_tag("Gemini.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Gemini <%= image_tag("gemini-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
  </tr> 

  <tr id="water-row">
    <td><h2 class="text-center">Water</h2></td>
    <td>
    <%= link_to sign_path("cancer")  do %>
    <%= image_tag("Cancer.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Cancer <%= image_tag("cancer-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
    <td>
    <%= link_to sign_path("scorpio")  do %>
      <%= image_tag("Scorpio.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Scorpio <%= image_tag("scorpio-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>
    <td>
    <%= link_to sign_path("pisces")  do %>
      <%= image_tag("Pisces.jpg", :alt => "rss feed", class: "sign-image hvr-grow") %>
      <h3 class="text-center">Pisces <%= image_tag("pisces-symbol.png", :alt => "rss feed", class: "symbol") %></h3>
      <% end %>
    </td>

  </tr>
</table><br><br>


<%= link_to " Created by EBM26", "http://www.eyalbenmoshe.com/", class: "my-name", :target => '_blank' %><br><br>
</body>

app/views/signs/show.html.erb
<body id="show-body">

  <h1 class="text-center"><u><%= @sign['name'] %></u></h1><h4 class="text-center"><u>(<%= @sign['date'] %>)</u></h4>

  <table id="show-table">
    <tr id="show-row-1">
      <th class="show-th"><h4><u>Basic Info</u></h4></th>
      <td id="name-show"><h3>The <%= @sign['name'] %> sign is the <%= @sign['stage'] %> stage of the <%= @sign['element'] %> element and is ruled by the <%= @sign['planet'] %> planet. In the Astrological Karmic Cycle <%= @sign['name'] %> represents the <%= @sign['karmic_stage'] %> stage. His life goal is to <%= @sign['life_goal'].downcase %>.</h3></td>
    </tr>

    <tr id="show-row-2">
      <th class="show-th"><h4><u>Appearance</u></h4></th>
      <td><h3><%= @sign['appearance'] %></h3></td>
    </tr>

    <tr id="show-row-3">
      <th class="show-th"><h4><u>Strenghts</u></h4></th>
      <td><h3><%= @sign['strengths'] %></h3></td>
    </tr>

    <tr id="show-row-4">
      <th class="show-th"><h4><u>Weaknesses</u></h4></th>
      <td><h3><%= @sign['weaknesses'] %></h3></td>
    </tr>

    <tr id="show-row-5">
      <th class="show-th"><h4><u>Hobbies</u></h4></th>
      <td><h3><%= @sign['hobbies'] %></h3></td>
    </tr>

    <tr id="show-row-6">
      <th class="show-th"><h4><u>Dislikes</u></h4></th>
      <td><h3><%= @sign['dislikes'] %></h3></td>
    </tr>

    <tr id="show-row-7">
      <th class="show-th"><h4><u>Key Words</u></h4></th>
      <td><h3><%= @sign['key_words'] %></h3></td>
    </tr>

    <tr id="show-row-8">
      <th class="show-th"><h4><u>Romance</u></h4></th>
      <td><h3><%= @sign['romance'] %></h3></td>
    </tr>

    <tr id="show-row-9">
      <th class="show-th"><h4><u>Tidbits</u></h4></th>
      <td><h3>This sign's color is <%= @sign['color'] %>, its lucky stone is <%= @sign['stone'] %>, its lucky metal is <%= @sign['metal'] %>, and its related body part is the <%= @sign['related_body_part'] %></h3></td>
    </tr>


  </table>

<%= link_to " Created by EBM26", "http://www.eyalbenmoshe.com/", class: "show-name", :target => '_blank' %>

  <h3 class="text-center"><%= link_to "Back to home page", signs_path, id: "home-link" %></h3><br><br>

</body>